### ISSUE TITLE
multitenant_decorator.rb and Raketask Error

### ISSUE THREAD

**Issue by Cloudinnovates** [stefansenk/spree_multi_tenant#6]
Hi , 
Thanks for the awesome app. 
I am new to Ruby on Rails. 
I followed the instruction and manually created multitenant_decorator.rb and tenant.rake file under lib/task

I get following error. 

Last login: Tue Jul 23 09:45:35 on ttys000
MACPRO:~ CloudInnovates$ cd store
MACPRO:store CloudInnovates$ subl ~/store/
MACPRO:store CloudInnovates$ rails server
WARNING: Nokogiri was built against LibXML version 2.7.3, but has dynamically loaded 2.7.8
=> Booting WEBrick
=> Rails 3.2.13 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/Users/CloudInnovates/store/app/models/multitenant_decorator.rb:2:in `<top (required)>': uninitialized constant Spree::Page (NameError)
    from /Users/CloudInnovates/store/config/application.rb:18:in`block (2 levels) in class:Application'
    from /Users/CloudInnovates/store/config/application.rb:17:in `glob'
    from /Users/CloudInnovates/store/config/application.rb:17:in`block in class:Application'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:506:in `_run__491926929473687932__prepare__39056507203998318__callbacks'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in`__run_callback'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in`run_callbacks'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/actionpack-3.2.13/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/actionpack-3.2.13/lib/action_dispatch/middleware/reloader.rb:48:in`prepare!'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.13/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.13/lib/rails/initializable.rb:30:in`instance_exec'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `run'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.13/lib/rails/initializable.rb:55:in`block in run_initializers'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `each'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.13/lib/rails/initializable.rb:54:in`run_initializers'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.13/lib/rails/application.rb:136:in `initialize!'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in`method_missing'
    from /Users/CloudInnovates/store/config/environment.rb:5:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/polyglot-0.3.3/lib/polyglot.rb:63:in`require'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
    from /Users/CloudInnovates/store/config.ru:3:in`block in <main>'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/builder.rb:51:in`initialize'
    from /Users/CloudInnovates/store/config.ru:in `new'
    from /Users/CloudInnovates/store/config.ru:in`<main>'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/builder.rb:40:in `eval'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/builder.rb:40:in`parse_file'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/server.rb:200:in `app'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.13/lib/rails/commands/server.rb:46:in`app'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/server.rb:304:in `wrapped_app'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/server.rb:254:in`start'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.13/lib/rails/commands/server.rb:70:in `start'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.13/lib/rails/commands.rb:55:in`block in <top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.13/lib/rails/commands.rb:50:in `tap'
    from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.13/lib/rails/commands.rb:50:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'
MACPRO:store CloudInnovates$ 

I have also added spree multi domain - https://github.com/spree/spree-multi-domain

none of this both works. 

Please Advice

Regards

**Comment by stefansenk** [comment]
Hi. The example in the readme using `Spree::Page` is intended to add multitenant to Pages in the https://github.com/spree/spree_static_content extension. You only need to add those models if you are using the extensions.

`Spree::Page` from https://github.com/spree/spree_static_content
`Spree::PaypalAccount` from https://github.com/spree/spree_paypal_express
`Spree::ProductGroup` from https://github.com/spree/spree_product_groups

**Comment by Cloudinnovates** [comment]
Hi 
Thanks for the advice. 
I have run into another problem. 
I followed the instruction and added the following code on RakeTask

but I am have the following error. 

SQLite3::SQLException: no such column: spree_pages.tenant_id: SELECT "spree_pages".\* FROM "spree_pages"  WHERE "spree_pages"."tenant_id" = 2 AND "spree_pages"."show_in_header" = 't' AND "spree_pages"."visible" = 't' ORDER BY position ASC

Rails server is running fine. 

The front and backend were showing perfectly if I did not add other spree plugins but I could not get the subdomain to work. 

I want users to register and add subdomain just like locomotivecms multisite so that they can their own front and backend. 

Please Advice

Regards

**Comment by stefansenk** [comment]
All the spree_pages stuff should only be required if you're using the https://github.com/spree/spree_static_content extension. Presumably you referencing spree pages in your code somewhere?

Regarding allowing users to register their own domains, you'll need to create your own page for that. It could work along the lines of the `create_tenant` raketask.
